# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    tags:
      - "**"
    branches:
      - "**"

jobs:
  build:
    name: Build GreenIT CLI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
      steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm link
      - name: Upload dist
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist



  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Download dist
      uses: actions/download-artifact@v2
      with:
          name: dist
          path: dist
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: gchapel/greenit-analysis-cli:${{ github.base_ref }}